# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# .NET CLI: https://docs.microsoft.com/dotnet/core/tools/
# Description: The purpose of this workflow is to compile YouRata.

name: Build

on:
  workflow_dispatch:

  #          ┌───────────── minute (0 - 59)
  #          │ ┌───────────── hour (0 - 23)
  #          │ │  ┌───────────── day of the month (1 - 31)
  #          │ │  │  ┌───────────── month (1 - 12 or JAN-DEC)
  #          │ │  │  │ ┌───────────── day of the week (0 - 6 or SUN-SAT)                                  
  #          │ │  │  │ │
  #          │ │  │  │ │
  schedule:
    - cron: '0 5 * * 6' # Time is UTC

jobs:
  build:
  
    permissions:
      contents: write
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./src/YouRata.sln
    # Build the solution
    - name: Build
      run: dotnet build ./src/YouRata.sln --no-restore
    # Create fake commit every 40 days of repository inactivity
    - name: Keepalive workflow
      uses: gautamkrishnar/keepalive-workflow@1.1.0
      with:
        commit_message: 'Repository inactivity detected'
        time_elapsed: 40
